---
packages_apt:
  - name: "containerd"
  - name: "dirmngr"
  - name: "dnsutils"
  - name: "docker"
  - name: "firefox"
    repo: "ppa:mozillateam/ppa"
    pref: |
      Package: *
      Pin: release o=LP-PPA-mozillateam
      Pin-Priority: 1001
      Package: firefox
      Pin: version 1:1snap1-0ubuntu2
      Pin-Priority: -1
  - name: "fwupd"
  - name: "gnupg-agent"
  - name: "gnupg2"
  - name: "hopenpgp-tools"
  - name: "libpam-u2f"
  - name: "libpam-yubico"
  - name: "modemmanager"
  - name: "net-tools"
  - name: "network-manager"
  - name: "nmap"
  - name: "pamu2fcfg"
  - name: "pcscd"
  - name: "scdaemon"
  - name: "wget"
  - name: "yubikey-manager"
  - name: "yubikey-personalization"
packages_dnf:
  - "ModemManager"
  - "bind-utils"
  - "cryptsetup"
  - "dirmngr"
  - "docker"
  - "fwupd"
  - "gnupg2"
  - "gnupg2-smime"
  - "net-tools"
  - "networkmanager"
  - "nmap"
  - "opensc"
  - "pam-u2f"
  - "pam_yubico"
  - "pamu2fcfg"
  - "pcsc-lite"
  - "pcsc-tools"
  - "pgp-tools"
  - "secure-delete"
  - "wget"
  - "ykpers"
  - "yubikey-manager"
packages_pacman:
  - "bind"
  - "ccid"
  - "docker"
  - "fwupd"
  - "github-cli"
  - "gnupg"
  - "hopenpgp-tools"
  - "modemmanager"
  - "net-tools"
  - "networkmanager"
  - "nmap"
  - "pam-u2f"
  - "pcsc-tools"
  - "pcsclite"
  - "wget"
  - "yubikey-manager"
  - "yubico-pam"
  - "yubikey-personalization"
packages_systemd:
  services:
    - "NetworkManager"
    - "bluetooth"
    - "containerd"
    - "docker"
    - "pcscd"
  sockets: ["pcscd"]
  timers: ["fstrim"]
