---
packages_apt:
  - "containerd"
  - "dirmngr"
  - "dnsutils"
  - "docker"
  - "firefox-esr"
  - "fwupd"
  - "gnupg-agent"
  - "gnupg2"
  # "hopenpgp-tools"
  - "libpam-u2f"
  - "libpam-yubico"
  - "modemmanager"
  - "net-tools"
  - "network-manager"
  - "nmap"
  - "pamu2fcfg"
  - "pcscd"
  - "scdaemon"
  - "wget"
  - "yubikey-manager"
  - "yubikey-personalization"
