line-length = 120
indent-width = 4
target-version = "py310"
exclude = [                                                                     # Exclude a variety of common dirs.
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
    ]

[lint]
select = [
    "A",                                                                        # flake8-builtins
    "ANN",                                                                      # flake8-annotations
    "ARG",                                                                      # flake8-unused-arguments
    "B",                                                                        # flake8-bugbear
    "BLE",                                                                      # flake8-bind-except
    "C4",                                                                       # flake8-comprehensions
    "C90",                                                                      # mccabe
    "COM",                                                                      # flake8-commas
    "D",                                                                        # pydocstyle
    "DTZ",                                                                      # flake8-datetimez
    "E",                                                                        # pycodestyle
    "EM",                                                                       # flake8-errmsg
    "ERA",                                                                      # eradicate
    "EXE",                                                                      # flake8-executable
    "F",                                                                        # pyflakes
    "FA",                                                                       # fastapi
    "FBT",                                                                      # flake8-boolean-trap
    "FLY",                                                                      # flynt
    "G",                                                                        # flake8-logging-format
    "I",                                                                        # isort
    "ICN",                                                                      # flake8-import-conventions
    "INP",                                                                      # flake8-no-pep420
    "ISC",                                                                      # flake8-implicit-str-concat
    "LOG",                                                                      # flake8-logging
    "N",                                                                        # pep8-naming
    "NPY",                                                                      # numpy
    "PD",                                                                       # pandas
    "PERF",                                                                     # perflint
    "PGH",                                                                      # pygrep-hooks
    "PIE",                                                                      # flake8-pie
#   "PL",                                                                       # 
    "PT",                                                                       # flake8-pytest-style
    "PTH",                                                                      # flake8-use-pathlib
    "Q",                                                                        # flake8-quotes
    "RET",                                                                      # flake8-return
    "RSE",                                                                      # flake8-raise
    "RUF",                                                                      # ruff
    "S",                                                                        # flake8-bandit
    "SIM",                                                                      # flake8-simplify
    "SLOT",                                                                     # flake8-slots
    "T10",                                                                      # flake8-debugger
    "T20",                                                                      # flake8-print
    "TCH",                                                                      # flake8-type-checking
    "TD",                                                                       # flake8-todos
    "TID",                                                                      # flake8-tidy-imports
    "TRY",                                                                      # tryceratops
    "W",                                                                        # pycodestyle
    "YTT",                                                                      # flake8-2020
    ]
ignore = [
    "AIR",                                                                      # airflow.
    "ANN1",                                                                     # flake8-annotations
    "COM812",                                                                   # missing-trailing-comma
    "CPY",                                                                      # flake8-copyright
    "D300",                                                                     # triple-single-quotes
    "DJ",                                                                       # django
    "G004",                                                                     # logging-f-string
    "INT",                                                                      # flake8-gettext
    "ISC001",                                                                   # single-line-implicit-string-concat...
    "PD011",                                                                    # pandas-use-of-dot-values
    "PD901",                                                                    # pandas-df-variable-name
    "PLR09",                                                                    # too-many-locals
    "PYI",                                                                      # flake8-pyi
    "Q001",                                                                     # bad-quotes-multiline-string
    "Q002",                                                                     # bad-quotes-docstring
    "S101",                                                                     # assert
    "S603",                                                                     # subprocess-without-shell-equals-true
    "SLF",                                                                      # private-member-access
    "T201",                                                                     # print
    "TD003",                                                                    # missing-todo-link
    "UP",                                                                       # pyupgrade
    ]
pydocstyle.convention = "google"                                                # Follow Google conventions.
fixable = ["ALL"]                                                               # Allow fix for all enabled rules.
unfixable = []
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"                    # Allow unused _VARs.

[lint.flake8-quotes]
docstring-quotes = "single"                                                     # Prefer single quotes
inline-quotes = "single"
multiline-quotes = "single"

[lint.mccabe]
max-complexity = 10                                                             # `C901` when complexity > 10.

[lint.per-file-ignores]
"test_*.py"=["INP001", "D100", "D103", "ANN201", "S101"]

[format]
quote-style = "single"                                                          # Prefer single quotes.
indent-style = "space"                                                          # Not tabs.
skip-magic-trailing-comma = false                                               # Respect trailing commas.
line-ending = "auto"                                                            # Auto-detect appropriate line ending.
