---
galaxy_info:
  author: "Casey Sparks"
  description: "Installs my preferred packages."
  issue_tracker_url: "https://github.com/caseysparkz/env/issues"
  license: "GPL-2.0-or-later"
  min_ansible_version: "2.17"
  galaxy_tags: ["linux"]
  platforms:
    - name: "Debian"
      versions: ["bookworm"]
dependencies: []
