---
galaxy_info:
  author: "Casey Sparks"
  description: "Configure auditd."
  issue_tracker_url: "https://github.com/caseysparkz/env/issues"
  license: "GPL-2.0-or-later"
  min_ansible_version: "2.17.10"
  galaxy_tags:
    - "auditd"
    - "linux"
    - "security"
  platforms:
    - name: "Debian"
      versions: ["bookworm"]
dependencies: []
