---
galaxy_info:
  author: "Casey Sparks"
  description: "Creates directories within the home dir."
  issue_tracker_url: "https://github.com/caseysparkz/env/issues"
  license: "GPL-2.0-or-later"
  min_ansible_version: "2.17.10"
  galaxy_tags:
    - "linux"
    - "filesystem"
  platforms:
    - name: "Debian"
      versions: ["bookworm"]
dependencies: []
