# Author:       Casey Sparks
# Date:         August 22, 2024
# Description:  Ensures that commit titles adhere to the Conventional Commit syntax.
---
name: "SemVer"
on:
  push:
    branches: ["main"]
jobs:
  tag_commit:
    name: "Apply Semantic Tags to Commits"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683"

      - name: "Tag commit"
        id: "ccv"
        uses: "smlx/ccv@7318e2f25a52dcd550e75384b84983973251a1f8"
        with:
          write-tag: true

      - name: "Echo changes to console"
        run: |
          echo "New tag:              ${{ steps.ccv.outputs.new-tag }}"
          echo "New tag version:      ${{ steps.ccv.outputs.new-tag-version }}"
          echo "New tag version type: ${{ steps.ccv.outputs.new-tag-version-type }}"
